[
    null,
    {"id":1,"battlerName":"Actor1_1","characterIndex":0,"characterName":"Mercenario","classId":1,"equips":[44,0,0,1,0],"faceIndex":0,"faceName":"Actor1","traits":[{"code":13,"dataId":3,"value":1}],"initialLevel":2,"maxLevel":97,"name":"Mercenario","nickname":"","note":"","profile":""},
    {"id":2,"battlerName":"girl1_1_battle","characterIndex":0,"characterName":"$Mujer","classId":3,"equips":[0,0,0,15,0],"faceIndex":3,"faceName":"Actor1","traits":[{"code":62,"dataId":2,"value":1}],"initialLevel":2,"maxLevel":99,"name":"Mujer","nickname":"","note":"","profile":""},
    {"id":3,"battlerName":"knight1_1","characterIndex":0,"characterName":"Caballero","classId":5,"equips":[7,18,0,14,0],"faceIndex":2,"faceName":"Actor1","traits":[{"code":13,"dataId":3,"value":1}],"initialLevel":2,"maxLevel":99,"name":"Caballero","nickname":"","note":"","profile":""},
]